# GitHub Sponsors & Funding Configuration
# https://github.com/sponsors/Nireus79

github: Nireus79

# Support Socrates development through GitHub Sponsors
# - $5/month → Pro tier features
# - $15/month → Enterprise tier features
