#!/usr/bin/env python
"""
Setup Socrates environment variables for first-time use.

This script:
1. Checks for required environment variables
2. Generates missing keys (JWT_SECRET_KEY, etc.)
3. Creates .env file with configuration
4. Validates setup is complete

Usage:
    python setup_env.py
"""

import os
import secrets
from pathlib import Path


def generate_jwt_secret():
    """Generate a secure JWT secret key"""
    return secrets.token_urlsafe(32)


def load_env_file(env_path):
    """Load existing .env file if it exists"""
    env_vars = {}
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    key, _, value = line.partition('=')
                    env_vars[key.strip()] = value.strip()
    return env_vars


def save_env_file(env_path, env_vars):
    """Save environment variables to .env file"""
    with open(env_path, 'w') as f:
        f.write("# Socrates Environment Configuration\n")
        f.write("# Generated by setup_env.py\n\n")

        for key, value in sorted(env_vars.items()):
            f.write(f"{key}={value}\n")


def setup_environment():
    """Setup Socrates environment"""
    env_file = Path('.env')

    print("=" * 70)
    print("SOCRATES ENVIRONMENT SETUP")
    print("=" * 70)

    # Load existing .env
    env_vars = load_env_file(env_file)

    # Check JWT_SECRET_KEY
    print("\n[1/3] Checking JWT_SECRET_KEY...")
    if 'JWT_SECRET_KEY' not in env_vars:
        print("  ⚠ JWT_SECRET_KEY not found")
        jwt_secret = generate_jwt_secret()
        env_vars['JWT_SECRET_KEY'] = jwt_secret
        print(f"  ✓ Generated: {jwt_secret[:20]}...")
    else:
        print(f"  ✓ Already set: {env_vars['JWT_SECRET_KEY'][:20]}...")

    # Check ANTHROPIC_API_KEY
    print("\n[2/3] Checking ANTHROPIC_API_KEY...")
    if 'ANTHROPIC_API_KEY' not in env_vars:
        api_key = os.getenv('ANTHROPIC_API_KEY')
        if api_key:
            env_vars['ANTHROPIC_API_KEY'] = api_key
            print(f"  ✓ Found from environment: {api_key[:20]}...")
        else:
            print("  ⚠ ANTHROPIC_API_KEY not set")
            print("  💡 Add your API key later in .env file")
            print("  💡 Or set: export ANTHROPIC_API_KEY='your-key'")
    else:
        print(f"  ✓ Already set: {env_vars['ANTHROPIC_API_KEY'][:20]}...")

    # Set other defaults
    print("\n[3/3] Setting defaults...")
    defaults = {
        'SOCRATES_DATA_DIR': '~/.socrates',
        'SOCRATES_API_HOST': '127.0.0.1',
        'SOCRATES_API_PORT': '8000',
        'ENVIRONMENT': 'development'
    }

    for key, default_value in defaults.items():
        if key not in env_vars:
            env_vars[key] = default_value
            print(f"  ✓ {key} = {default_value}")
        else:
            print(f"  ✓ {key} = {env_vars[key]} (existing)")

    # Save .env file
    print("\n[SAVE] Writing .env file...")
    save_env_file(env_file, env_vars)
    print(f"  ✓ Saved to {env_file.absolute()}")

    # Summary
    print("\n" + "=" * 70)
    print("SETUP COMPLETE ✓")
    print("=" * 70)
    print("\nNext steps:")
    print("  1. (Optional) Add your ANTHROPIC_API_KEY to .env")
    print("  2. Run: python socrates.py --full")
    print("  3. Open browser to http://localhost:5173")
    print("\n" + "=" * 70)


if __name__ == "__main__":
    setup_environment()
