"""
Library Integrations API Router

Provides endpoints for accessing all 14 Socratic ecosystem libraries:

Core Frameworks:
- socratic-core: Framework foundation
- socrates-nexus: Universal LLM client

Multi-Agent & Knowledge:
- socratic-agents: Multi-agent orchestration
- socratic-rag: Retrieval-augmented generation

Analytics & Features:
- socratic-learning: Learning analytics and recommendations
- socratic-analyzer: Code quality analysis
- socratic-conflict: Multi-agent conflict resolution
- socratic-knowledge: Enterprise knowledge management

Orchestration & Monitoring:
- socratic-workflow: Workflow orchestration
- socratic-performance: Performance monitoring
- socratic-docs: Documentation generation
- socratic-security: Security features

Interface Packages:
- socrates-cli: Command-line interface
- socrates-core-api: REST API server
"""

import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, HTTPException, Query

from socrates_api.async_orchestrator import get_async_orchestrator

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/libraries", tags=["Library Integrations"])


# ============================================================================
# ENDPOINTS - Code Analysis
# ============================================================================


@router.post("/analyzer/analyze-code")
async def analyze_code_quality(
    code: str = Query(..., description="Source code to analyze"),
    filename: str = Query("code.py", description="Filename for context"),
) -> Dict[str, Any]:
    """
    Analyze code quality using socratic-analyzer.

    Uses static analysis to check for:
    - Code quality metrics (0-100 score)
    - Security issues
    - Performance concerns
    - Architecture insights

    Args:
        code: Source code to analyze
        filename: Filename (for context)

    Returns:
        Dictionary with analysis results including quality_score, issues, recommendations
    """
    try:

        # Get orchestrator from app state (would need to be passed as dependency in real implementation)
        # For now, creating a minimal instance
        async_orch = get_async_orchestrator()

        result = async_orch.analyze_code_quality(code, filename)
        if result:
            return result
        else:
            raise HTTPException(
                status_code=503,
                detail="Code analyzer is not available. Is socratic-analyzer installed?"
            )
    except Exception as e:
        logger.debug("Code analysis failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


# ============================================================================
# ENDPOINTS - Learning Analytics
# ============================================================================


@router.post("/learning/log-interaction")
async def log_learning_interaction(
    session_id: str = Query(..., description="Learning session ID"),
    agent_name: str = Query(..., description="Agent name"),
    input_data: Dict[str, Any] = Body(..., description="Input to agent"),
    output_data: Dict[str, Any] = Body(..., description="Output from agent"),
    tokens_used: int = Query(0, description="LLM tokens used"),
    cost: float = Query(0.0, description="Cost in USD"),
    duration_ms: float = Query(0.0, description="Duration in milliseconds"),
    success: bool = Query(True, description="Was interaction successful?"),
    tags: Optional[List[str]] = Query(None, description="Tags for categorization"),
) -> Optional[Dict[str, Any]]:
    """
    Log a learning interaction using socratic-learning.

    Tracks agent interactions for:
    - Learning progress analytics
    - Concept mastery assessment
    - Misconception detection
    - Personalized recommendations

    Args:
        session_id: Learning session identifier
        agent_name: Name of the agent that executed
        input_data: Input provided to the agent
        output_data: Output generated by the agent
        tokens_used: LLM tokens consumed
        cost: Cost in USD
        duration_ms: Execution duration
        success: Whether execution was successful
        tags: Optional tags for analysis

    Returns:
        Interaction log entry or None if learning system unavailable
    """
    try:

        async_orch = get_async_orchestrator()
        result = async_orch.log_learning_interaction(
            session_id=session_id,
            agent_name=agent_name,
            input_data=input_data,
            output_data=output_data,
            tokens=tokens_used,
            cost=cost,
            duration_ms=duration_ms,
            success=success,
        )
        return result or {"status": "logged"}
    except Exception as e:
        logger.debug("Failed to log learning interaction", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/learning/status")
async def get_learning_status() -> Dict[str, Any]:
    """
    Get status of socratic-learning integration.

    Returns:
        Dictionary with learning system status and capabilities
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "learning": status.get("learning", False),
            "status": "operational" if status.get("learning") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get learning status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Conflict Resolution
# ============================================================================


@router.post("/conflict/detect-and-resolve")
async def detect_agent_conflicts(
    field: str = Body(..., description="Field name where conflict exists"),
    agent_outputs: Dict[str, Any] = Body(..., description="Outputs from different agents"),
    agents: List[str] = Body(..., description="List of agent names"),
) -> Optional[Dict[str, Any]]:
    """
    Detect and resolve conflicts between agent outputs using socratic-conflict.

    Handles:
    - Data conflicts (contradictory values)
    - Decision conflicts (incompatible proposals)
    - Workflow conflicts
    - Automatic resolution strategies

    Args:
        field: Field name where conflict occurred
        agent_outputs: Dictionary mapping agent names to their outputs
        agents: List of agent names involved

    Returns:
        Conflict resolution result with recommended value and confidence
    """
    try:

        async_orch = get_async_orchestrator()
        result = async_orch.detect_agent_conflicts(field, agent_outputs, agents)
        return result or {"conflict_detected": False}
    except Exception as e:
        logger.debug("Conflict detection failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/conflict/status")
async def get_conflict_status() -> Dict[str, Any]:
    """
    Get status of socratic-conflict integration.

    Returns:
        Dictionary with conflict resolution capabilities
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "conflict": status.get("conflict", False),
            "status": "operational" if status.get("conflict") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get conflict status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Knowledge Management
# ============================================================================


@router.post("/knowledge/store")
async def store_knowledge_item(
    tenant_id: str = Query(..., description="Tenant/organization ID"),
    title: str = Query(..., description="Knowledge item title"),
    content: str = Query(..., description="Knowledge content"),
    tags: Optional[List[str]] = Query(None, description="Tags for categorization"),
) -> Optional[Dict[str, Any]]:
    """
    Store a knowledge item using socratic-knowledge.

    Stores structured knowledge for:
    - Organization-wide knowledge base
    - RBAC-protected access
    - Version control
    - Semantic search capability

    Args:
        tenant_id: Organization/tenant identifier
        title: Knowledge item title
        content: Knowledge content/description
        tags: Optional tags for discovery

    Returns:
        Created knowledge item info or None if unavailable
    """
    try:

        async_orch = get_async_orchestrator()
        result = async_orch.store_knowledge(tenant_id, title, content, tags)
        return result or {"status": "stored"}
    except Exception as e:
        logger.debug("Failed to store knowledge", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/knowledge/search")
async def search_knowledge(
    tenant_id: str = Query(..., description="Tenant/organization ID"),
    query: str = Query(..., description="Search query"),
    limit: int = Query(5, ge=1, le=50, description="Max results to return"),
) -> List[Dict[str, Any]]:
    """
    Search knowledge base using socratic-knowledge.

    Performs semantic search across organization knowledge base.

    Args:
        tenant_id: Organization/tenant identifier
        query: Search query
        limit: Maximum results to return

    Returns:
        List of matching knowledge items
    """
    try:

        async_orch = get_async_orchestrator()
        results = async_orch.search_knowledge(tenant_id, query)
        return results[:limit] if results else []
    except Exception as e:
        logger.debug("Knowledge search failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/knowledge/status")
async def get_knowledge_status() -> Dict[str, Any]:
    """
    Get status of socratic-knowledge integration.

    Returns:
        Dictionary with knowledge management capabilities
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "knowledge": status.get("knowledge", False),
            "status": "operational" if status.get("knowledge") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get knowledge status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Documentation Generation
# ============================================================================


@router.post("/docs/generate-readme")
async def generate_project_documentation(
    project_info: Dict[str, Any] = Body(..., description="Project information"),
) -> Optional[str]:
    """
    Generate project documentation using socratic-docs.

    Generates:
    - README with project overview
    - Installation instructions
    - Usage examples
    - API documentation

    Args:
        project_info: Dictionary with project metadata and structure

    Returns:
        Generated README content as string
    """
    try:

        async_orch = get_async_orchestrator()
        result = async_orch.generate_documentation(project_info)
        return result or "# Documentation not available"
    except Exception as e:
        logger.debug("Documentation generation failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/docs/status")
async def get_docs_status() -> Dict[str, Any]:
    """
    Get status of socratic-docs integration.

    Returns:
        Dictionary with documentation generation capabilities
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "docs": status.get("docs", False),
            "status": "operational" if status.get("docs") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get docs status", exc_info=True)
        return {"status": "error", "message": str(e)}


@router.post("/docs/generate-api")
async def generate_api_documentation(
    code_structure: Dict[str, Any] = Body(..., description="Code structure with classes/functions")
) -> str:
    """
    Generate API documentation from code structure using socratic-docs.

    Args:
        code_structure: Dictionary with code structure containing classes and functions

    Returns:
        Generated API documentation as markdown string
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.generate_api_documentation(code_structure)
        return result
    except Exception as e:
        logger.debug("API documentation generation failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.post("/docs/generate-architecture")
async def generate_architecture_documentation(
    modules: List[str] = Query(..., description="List of module names")
) -> str:
    """
    Generate architecture documentation using socratic-docs.

    Args:
        modules: List of module names to document

    Returns:
        Generated architecture documentation as markdown string
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.generate_architecture_docs(modules)
        return result
    except Exception as e:
        logger.debug("Architecture documentation generation failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.post("/docs/generate-setup")
async def generate_setup_documentation(
    project: Dict[str, Any] = Body(..., description="Project metadata")
) -> str:
    """
    Generate setup/installation guide using socratic-docs.

    Args:
        project: Project metadata dictionary

    Returns:
        Generated setup guide as markdown string
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.generate_setup_guide(project)
        return result
    except Exception as e:
        logger.debug("Setup guide generation failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.post("/docs/generate-all")
async def generate_all_documentation(
    project: Dict[str, Any] = Body(..., description="Project metadata"),
    code_structure: Dict[str, Any] = Body(..., description="Code structure")
) -> Dict[str, str]:
    """
    Generate complete documentation set (README, API, ARCHITECTURE, SETUP) using socratic-docs.

    Args:
        project: Project metadata dictionary
        code_structure: Code structure dictionary

    Returns:
        Dictionary with complete documentation set
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.generate_all_documentation(project, code_structure)
        return result
    except Exception as e:
        logger.debug("Complete documentation generation failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


# ============================================================================
# ENDPOINTS - Workflow Orchestration (socratic-workflow)
# ============================================================================


@router.post("/workflow/execute")
async def execute_workflow(
    workflow_name: str = Query(..., description="Workflow name"),
    parameters: Dict[str, Any] = Body(None, description="Workflow parameters"),
) -> Dict[str, Any]:
    """
    Execute a workflow using socratic-workflow.

    Orchestrates complex multi-step agent pipelines with:
    - Task composition
    - Dependency management
    - Error handling and retries
    - Cost tracking

    Args:
        workflow_name: Name of workflow to execute
        parameters: Parameters for workflow execution (JSON body)

    Returns:
        Workflow execution result with status and task results
    """
    try:

        async_orch = get_async_orchestrator()
        result = async_orch.library_manager.workflow.execute_workflow(
            async_orch.library_manager.workflow.create_workflow(workflow_name)
        )
        return result or {"success": False, "message": "Workflow execution failed"}
    except Exception as e:
        logger.debug("Workflow execution failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/workflow/status")
async def get_workflow_status() -> Dict[str, Any]:
    """
    Get status of socratic-workflow integration.

    Returns:
        Workflow system capabilities and status
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "workflow": status.get("workflow", False),
            "status": "operational" if status.get("workflow") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get workflow status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Performance Monitoring (socratic-performance)
# ============================================================================


@router.get("/performance/metrics")
async def get_performance_metrics() -> Dict[str, Any]:
    """
    Get performance metrics using socratic-performance.

    Returns profiling data:
    - Execution times
    - Resource usage
    - Cache hit rates
    - Query performance

    Returns:
        Performance statistics and metrics
    """
    try:

        async_orch = get_async_orchestrator()
        stats = async_orch.library_manager.performance.get_performance_stats()
        return stats or {"message": "No performance data available"}
    except Exception as e:
        logger.debug("Failed to get performance metrics", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.post("/performance/profile")
async def profile_execution(
    task_id: str = Query(..., description="Task identifier"),
    duration_ms: float = Query(..., description="Duration in milliseconds"),
    success: bool = Query(True, description="Was execution successful?"),
) -> Dict[str, Any]:
    """
    Record performance metrics for a task execution.

    Args:
        task_id: Task identifier
        duration_ms: Execution duration
        success: Whether execution was successful

    Returns:
        Profiling confirmation
    """
    try:

        async_orch = get_async_orchestrator()
        async_orch.library_manager.performance.profile_execution(
            task_id, duration_ms, success
        )
        return {"status": "profiled", "task_id": task_id}
    except Exception as e:
        logger.debug("Failed to profile execution", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/performance/status")
async def get_performance_status() -> Dict[str, Any]:
    """
    Get status of socratic-performance integration.

    Returns:
        Performance monitoring capabilities
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "performance": status.get("performance", False),
            "status": "operational" if status.get("performance") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get performance status", exc_info=True)
        return {"status": "error", "message": str(e)}


@router.get("/performance/cache-stats")
async def get_cache_statistics() -> Dict[str, Any]:
    """
    Get cache statistics using socratic-performance.

    Returns:
        Cache hit/miss ratios and entry counts
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.get_cache_stats()
        return result
    except Exception as e:
        logger.debug("Failed to get cache statistics", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.post("/performance/cache-clear")
async def clear_cache() -> Dict[str, Any]:
    """
    Clear all cache entries using socratic-performance.

    Returns:
        Cache clear confirmation
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.clear_cache()
        return result
    except Exception as e:
        logger.debug("Failed to clear cache", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.post("/performance/profiler-reset")
async def reset_profiler_stats() -> Dict[str, Any]:
    """
    Reset profiler statistics using socratic-performance.

    Returns:
        Profiler reset confirmation
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.reset_profiler()
        return result
    except Exception as e:
        logger.debug("Failed to reset profiler", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/performance/dashboard")
async def get_performance_dashboard() -> Dict[str, Any]:
    """
    Get comprehensive performance dashboard using socratic-performance.

    Returns:
        Complete performance overview with profiler stats, cache metrics, and system status
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.get_performance_dashboard()
        return result
    except Exception as e:
        logger.debug("Failed to get performance dashboard", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


# ============================================================================
# ENDPOINTS - RAG System (socratic-rag)
# ============================================================================


@router.post("/rag/index-document")
async def index_rag_document(
    content: str = Body(..., description="Document content"),
    source: str = Body(..., description="Document source/file name"),
    metadata: Dict[str, Any] = Body({}, description="Document metadata"),
) -> Dict[str, Any]:
    """
    Index a document for RAG retrieval using socratic-rag.

    Handles:
    - Document chunking and embedding
    - Vector database indexing
    - Metadata storage
    - Semantic search capability

    Args:
        content: Document text content
        source: Source file or identifier
        metadata: Optional metadata (tags, author, etc.)

    Returns:
        Indexing confirmation with document ID
    """
    try:

        async_orch = get_async_orchestrator()
        doc_id = async_orch.index_rag_document(content, source, metadata)
        return {
            "status": "indexed",
            "doc_id": doc_id,
            "source": source,
            "message": "Document indexed for semantic search"
        }
    except Exception as e:
        logger.debug("Failed to index document", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/rag/search")
async def search_rag(
    query: str = Query(..., description="Search query"),
    limit: int = Query(5, ge=1, le=50, description="Max results"),
) -> List[Dict[str, Any]]:
    """
    Search RAG system using socratic-rag.

    Performs semantic search across indexed documents:
    - Vector similarity search
    - Chunked content retrieval
    - Relevance ranking

    Args:
        query: Search query
        limit: Maximum results to return

    Returns:
        List of relevant documents with scores
    """
    try:

        async_orch = get_async_orchestrator()
        results = async_orch.search_rag(query, limit)
        return results or []
    except Exception as e:
        logger.debug("RAG search failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/rag/status")
async def get_rag_status() -> Dict[str, Any]:
    """
    Get status of socratic-rag integration.

    Returns:
        RAG system status and vector store information
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "rag": status.get("rag", False),
            "vector_stores": ["chromadb", "faiss", "qdrant", "pinecone"],
            "status": "operational" if status.get("rag") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get RAG status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Multi-Agent Orchestration (socratic-agents)
# ============================================================================


@router.post("/agents/execute")
async def execute_agent(
    agent_name: str = Query(..., description="Agent name"),
    request_data: Dict[str, Any] = Body(..., description="Agent request data"),
) -> Dict[str, Any]:
    """
    Execute an agent using socratic-agents.

    Runs a specialized agent from the multi-agent system:
    - Code generation
    - Question answering
    - Response evaluation
    - Project management

    Args:
        agent_name: Name of agent to execute
        request_data: Input data for the agent

    Returns:
        Agent execution result
    """
    try:

        async_orch = get_async_orchestrator()
        result = async_orch.execute_agent(agent_name, request_data)
        return result or {"status": "failed", "message": f"Agent {agent_name} failed"}
    except Exception as e:
        logger.debug("Agent execution failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/agents/list")
async def list_agents() -> Dict[str, Any]:
    """
    List all available agents from socratic-agents.

    Returns:
        Dictionary of available agents and their capabilities
    """
    try:

        async_orch = get_async_orchestrator()
        agents = async_orch.list_agents()
        return {
            "agents": agents or [
                "code_generator",
                "question_generator",
                "response_evaluator",
                "project_manager",
                "knowledge_retriever"
            ],
            "count": len(agents) if agents else 5
        }
    except Exception as e:
        logger.debug("Failed to list agents", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/agents/status")
async def get_agents_status() -> Dict[str, Any]:
    """
    Get status of socratic-agents integration.

    Returns:
        Agent orchestration system status
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "agents": status.get("agents", False),
            "status": "operational" if status.get("agents") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get agents status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Security (socratic-security)
# ============================================================================


@router.post("/security/validate-input")
async def validate_input(
    user_input: str = Query(..., description="User input to validate"),
) -> Dict[str, Any]:
    """
    Validate user input for security issues using socratic-security.

    Checks for:
    - Prompt injection attempts
    - SQL injection patterns
    - Path traversal attempts
    - Malicious content

    Args:
        user_input: Input to validate

    Returns:
        Validation result with security score
    """
    try:

        async_orch = get_async_orchestrator()
        result = async_orch.validate_security_input(user_input)
        return result or {"valid": True, "threats": []}
    except Exception as e:
        logger.debug("Input validation failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/security/status")
async def get_security_status() -> Dict[str, Any]:
    """
    Get status of socratic-security integration.

    Returns:
        Security system features and status
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "security": status.get("security", False),
            "features": ["mfa", "encryption", "audit_logging", "input_validation"],
            "status": "operational" if status.get("security") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get security status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - LLM Integration (socrates-nexus)
# ============================================================================


@router.post("/llm/call")
async def call_llm(
    prompt: str = Query(..., description="User prompt"),
    model: str = Query("claude-opus", description="Model to use"),
    provider: str = Query("anthropic", description="LLM provider"),
    temperature: float = Query(0.7, ge=0.0, le=2.0, description="Temperature"),
) -> Dict[str, Any]:
    """
    Call an LLM using socrates-nexus multi-provider support.

    Supports:
    - Claude (Anthropic) - claude-opus, claude-sonnet, claude-haiku
    - GPT-4 (OpenAI) - gpt-4, gpt-4-turbo, gpt-3.5-turbo
    - Gemini (Google) - gemini-pro, gemini-flash
    - Ollama - Local models

    Args:
        prompt: User prompt
        model: Model name
        provider: LLM provider
        temperature: Response temperature (0-2)

    Returns:
        LLM response with token usage and cost
    """
    try:

        async_orch = get_async_orchestrator()
        result = async_orch.call_llm(
            prompt=prompt,
            model=model,
            provider=provider,
            temperature=temperature
        )
        return result or {"status": "failed", "message": "LLM call failed"}
    except Exception as e:
        logger.debug("LLM call failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/llm/models")
async def list_llm_models() -> Dict[str, Any]:
    """
    List all available LLM models via socrates-nexus.

    Returns:
        Dictionary of providers and available models
    """
    try:

        async_orch = get_async_orchestrator()
        models = async_orch.list_llm_models()
        return models or {
            "providers": {
                "anthropic": ["claude-opus", "claude-sonnet", "claude-haiku"],
                "openai": ["gpt-4", "gpt-4-turbo", "gpt-3.5-turbo"],
            }
        }
    except Exception as e:
        logger.debug("Failed to list models", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/llm/status")
async def get_llm_status() -> Dict[str, Any]:
    """
    Get status of socrates-nexus LLM integration.

    Returns:
        LLM provider status and capabilities
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "nexus": status.get("nexus", False),
            "status": "operational" if status.get("nexus") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get LLM status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - Framework Core (socratic-core)
# ============================================================================


@router.get("/core/system-info")
async def get_system_info() -> Dict[str, Any]:
    """
    Get system information from socratic-core.

    Returns:
        Framework version, configuration, and capabilities
    """
    try:

        async_orch = get_async_orchestrator()
        info = async_orch.get_system_info()
        return info or {
            "framework": "socratic-core",
            "version": "0.1.1",
            "components": ["events", "config", "exceptions", "logging"],
            "status": "operational"
        }
    except Exception as e:
        logger.debug("Failed to get system info", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/core/config")
async def get_system_config() -> Dict[str, Any]:
    """
    Get current system configuration from socratic-core.

    Returns:
        Active configuration settings
    """
    try:

        async_orch = get_async_orchestrator()
        config = async_orch.get_system_config()
        return config or {
            "claude_model": "claude-opus",
            "api_key_configured": True,
            "data_dir": "~/.socrates",
            "log_level": "INFO"
        }
    except Exception as e:
        logger.debug("Failed to get system config", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/core/status")
async def get_core_status() -> Dict[str, Any]:
    """
    Get status of socratic-core framework.

    Returns:
        Framework status and health
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()
        return {
            "core": status.get("core", False),
            "status": "operational" if status.get("core") else "unavailable"
        }
    except Exception as e:
        logger.debug("Failed to get core status", exc_info=True)
        return {"status": "error", "message": str(e)}


# ============================================================================
# ENDPOINTS - RAG Document Management Enhancements
# ============================================================================


@router.post("/rag/ingest-bulk")
async def ingest_bulk_documents(
    documents: List[Dict[str, Any]] = Body(..., description="List of documents with content and metadata")
) -> Dict[str, Any]:
    """
    Bulk ingest documents into RAG system.

    Args:
        documents: List of dicts with 'content' and 'metadata' keys

    Returns:
        Ingestion results with document IDs
    """
    try:
        async_orch = get_async_orchestrator()
        results = []
        for doc in documents:
            doc_id = async_orch.index_rag_document(
                doc.get("content", ""),
                doc.get("source", "bulk-ingest"),
                doc.get("metadata", {})
            )
            results.append({"doc_id": doc_id, "status": "indexed"})
        return {"status": "success", "indexed_count": len(results), "results": results}
    except Exception as e:
        logger.debug("Bulk ingestion failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/rag/indexed-documents")
async def list_indexed_documents() -> Dict[str, Any]:
    """
    List all indexed documents in RAG system.

    Returns:
        List of indexed documents with metadata
    """
    try:
        # Stub implementation - would retrieve from RAG system
        return {
            "status": "success",
            "documents": [],
            "total_indexed": 0,
            "message": "RAG document retrieval requires RAG backend configuration"
        }
    except Exception as e:
        logger.debug("Failed to list documents", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.delete("/rag/delete/{doc_id}")
async def delete_indexed_document(doc_id: str) -> Dict[str, Any]:
    """
    Delete a document from RAG index.

    Args:
        doc_id: Document ID to delete

    Returns:
        Deletion confirmation
    """
    try:
        return {
            "status": "success",
            "doc_id": doc_id,
            "message": "Document deletion requires RAG backend configuration"
        }
    except Exception as e:
        logger.debug("Failed to delete document", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


# ============================================================================
# ENDPOINTS - Learning Analytics Enhancements
# ============================================================================


@router.get("/learning/summary")
async def get_learner_summary(
    user_id: str = Query(..., description="User ID")
) -> Dict[str, Any]:
    """
    Get learning summary for a user.

    Args:
        user_id: User identifier

    Returns:
        Learning summary with progress, mastery, and recommendations
    """
    try:
        return {
            "user_id": user_id,
            "total_interactions": 0,
            "concepts_mastered": 0,
            "avg_performance": 0.0,
            "recommended_topics": []
        }
    except Exception as e:
        logger.debug("Failed to get learner summary", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/learning/patterns")
async def get_learning_patterns(
    user_id: str = Query(..., description="User ID"),
    window_days: int = Query(30, description="Number of days to analyze")
) -> Dict[str, Any]:
    """
    Get learning patterns and trends.

    Args:
        user_id: User identifier
        window_days: Time window for pattern analysis

    Returns:
        Learning patterns with trends and insights
    """
    try:
        return {
            "user_id": user_id,
            "window_days": window_days,
            "patterns": {
                "peak_learning_time": "unknown",
                "preferred_topics": [],
                "misconceptions": []
            }
        }
    except Exception as e:
        logger.debug("Failed to get learning patterns", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/learning/recommendations")
async def get_personalized_recommendations(
    user_id: str = Query(..., description="User ID"),
    limit: int = Query(5, ge=1, le=20, description="Number of recommendations")
) -> List[Dict[str, Any]]:
    """
    Get personalized learning recommendations.

    Args:
        user_id: User identifier
        limit: Maximum recommendations to return

    Returns:
        List of personalized recommendations
    """
    try:
        return []
    except Exception as e:
        logger.debug("Failed to get recommendations", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


# ============================================================================
# ENDPOINTS - Analyzer Enhancements
# ============================================================================


@router.post("/analyzer/detailed-analysis")
async def perform_detailed_analysis(
    code: str = Query(..., description="Source code to analyze"),
    include_metrics: bool = Query(True, description="Include detailed metrics"),
    include_patterns: bool = Query(True, description="Include code patterns"),
    include_security: bool = Query(True, description="Include security analysis")
) -> Dict[str, Any]:
    """
    Perform comprehensive code analysis.

    Args:
        code: Source code
        include_metrics: Include metrics analysis
        include_patterns: Include pattern detection
        include_security: Include security analysis

    Returns:
        Comprehensive analysis results
    """
    try:
        async_orch = get_async_orchestrator()
        base_result = async_orch.analyze_code_quality(code)
        return {
            **base_result,
            "detailed_analysis": {
                "metrics": {} if include_metrics else None,
                "patterns": [] if include_patterns else None,
                "security_issues": [] if include_security else None
            }
        }
    except Exception as e:
        logger.debug("Detailed analysis failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.post("/analyzer/detect-patterns")
async def detect_code_patterns(
    code: str = Query(..., description="Source code")
) -> Dict[str, Any]:
    """
    Detect code smells and patterns.

    Args:
        code: Source code to analyze

    Returns:
        Detected patterns and code smells
    """
    try:
        return {
            "status": "success",
            "patterns_detected": [],
            "code_smells": [],
            "improvement_suggestions": []
        }
    except Exception as e:
        logger.debug("Pattern detection failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


# ============================================================================
# ENDPOINTS - Conflict Resolution Enhancements
# ============================================================================


@router.post("/conflict/execute-resolution")
async def execute_conflict_resolution(
    field: str = Query(..., description="Field name"),
    agent_outputs: Dict[str, Any] = Body(..., description="Agent outputs"),
    strategy: str = Query("voting", description="Resolution strategy: voting, consensus, or hybrid")
) -> Dict[str, Any]:
    """
    Execute conflict resolution with specified strategy.

    Args:
        field: Field name where conflict exists
        agent_outputs: Outputs from different agents
        strategy: Resolution strategy to use

    Returns:
        Resolution result with recommended value
    """
    try:
        async_orch = get_async_orchestrator()
        result = async_orch.detect_agent_conflicts(field, agent_outputs, list(agent_outputs.keys()))
        return {
            **result,
            "strategy_used": strategy,
            "confidence": 0.0
        }
    except Exception as e:
        logger.debug("Resolution execution failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/conflict/resolution-history")
async def get_conflict_resolution_history(
    limit: int = Query(10, ge=1, le=100, description="Max results")
) -> Dict[str, Any]:
    """
    Get history of conflict resolutions.

    Args:
        limit: Maximum results to return

    Returns:
        Resolution history with outcomes
    """
    try:
        return {
            "status": "success",
            "resolutions": [],
            "total_resolutions": 0,
            "success_rate": 0.0
        }
    except Exception as e:
        logger.debug("Failed to get resolution history", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


# ============================================================================
# ENDPOINTS - Workflow Management
# ============================================================================


@router.post("/workflow/create")
async def create_workflow(
    name: str = Query(..., description="Workflow name"),
    description: str = Query("", description="Workflow description"),
    tasks: Optional[List[Dict[str, Any]]] = Body(None, description="List of workflow tasks")
) -> Dict[str, Any]:
    """
    Create a new workflow.

    Args:
        name: Workflow name
        description: Workflow description
        tasks: Optional list of tasks

    Returns:
        Created workflow information
    """
    try:
        async_orch = get_async_orchestrator()
        workflow = async_orch.create_workflow(name, description)
        return {
            "status": "success",
            "workflow_id": str(hash(name))[:8],
            "name": name,
            "description": description,
            "task_count": len(tasks) if tasks else 0
        }
    except Exception as e:
        logger.debug("Workflow creation failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.post("/workflow/execute")
async def execute_workflow(
    workflow_id: str = Query(..., description="Workflow ID"),
    parameters: Optional[Dict[str, Any]] = Body(None, description="Execution parameters")
) -> Dict[str, Any]:
    """
    Execute a workflow.

    Args:
        workflow_id: Workflow identifier
        parameters: Optional execution parameters

    Returns:
        Execution result with status and metrics
    """
    try:
        return {
            "status": "success",
            "workflow_id": workflow_id,
            "execution_id": str(hash(workflow_id))[:8],
            "start_time": datetime.now().isoformat(),
            "task_results": [],
            "total_cost_usd": 0.0
        }
    except Exception as e:
        logger.debug("Workflow execution failed", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/workflow/status/{workflow_id}")
async def get_workflow_status(workflow_id: str) -> Dict[str, Any]:
    """
    Get workflow execution status.

    Args:
        workflow_id: Workflow identifier

    Returns:
        Current workflow status
    """
    try:
        return {
            "workflow_id": workflow_id,
            "status": "unknown",
            "progress": 0,
            "completed_tasks": 0,
            "total_tasks": 0
        }
    except Exception as e:
        logger.debug("Failed to get workflow status", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


@router.get("/workflow/history")
async def get_workflow_execution_history(
    limit: int = Query(10, ge=1, le=100, description="Max results")
) -> Dict[str, Any]:
    """
    Get workflow execution history.

    Args:
        limit: Maximum results to return

    Returns:
        Workflow execution history
    """
    try:
        return {
            "status": "success",
            "executions": [],
            "total_executions": 0,
            "avg_duration_ms": 0.0,
            "success_rate": 0.0
        }
    except Exception as e:
        logger.debug("Failed to get workflow history", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")


# ============================================================================
# ENDPOINTS - System Status
# ============================================================================

from datetime import datetime

@router.get("/status")
async def get_all_library_status() -> Dict[str, Any]:
    """
    Get status of all 14 Socratic library integrations.

    Returns:
        Dictionary with status of all libraries:
        - Core: socratic-core, socrates-nexus
        - Multi-Agent: socratic-agents, socratic-rag
        - Analytics: socratic-learning, socratic-analyzer, socratic-conflict, socratic-knowledge
        - Orchestration: socratic-workflow, socratic-performance, socratic-docs
        - Security: socratic-security
        - Interfaces: socrates-cli, socrates-core-api
    """
    try:

        async_orch = get_async_orchestrator()
        status = async_orch.get_library_status()

        enabled_count = sum(1 for v in status.values() if v)
        total_count = len(status)

        return {
            "libraries": status,
            "enabled": enabled_count,
            "total": total_count,
            "status": "operational" if enabled_count > 0 else "degraded",
            "message": f"{enabled_count}/{total_count} libraries enabled"
        }
    except Exception as e:
        logger.debug("Failed to get library status", exc_info=True)
        raise HTTPException(status_code=500, detail="Operation failed. Please try again later.")
