"""
Standardized Error Codes for Socrates API

This module defines all error codes used throughout the API.
Error codes are machine-readable strings that allow clients to
programmatically handle different error scenarios.

Codes are organized by category and HTTP status code.
"""

# ============================================================================
# 4xx Client Errors
# ============================================================================

# 400 Bad Request / Validation Errors
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_INPUT = "INVALID_INPUT"
MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_PROJECT_TYPE = "INVALID_PROJECT_TYPE"
INVALID_PHASE = "INVALID_PHASE"
INVALID_SUBSCRIPTION_TIER = "INVALID_SUBSCRIPTION_TIER"

# 401 Unauthorized / Authentication Errors
AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
TOKEN_INVALID = "TOKEN_INVALID"
MISSING_AUTH_HEADER = "MISSING_AUTH_HEADER"

# 403 Forbidden / Authorization Errors
UNAUTHORIZED = "UNAUTHORIZED"
INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
ACCESS_DENIED = "ACCESS_DENIED"
INSUFFICIENT_SUBSCRIPTION = "INSUFFICIENT_SUBSCRIPTION"

# 404 Not Found Errors
NOT_FOUND = "NOT_FOUND"
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
USER_NOT_FOUND = "USER_NOT_FOUND"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND"
NOTE_NOT_FOUND = "NOTE_NOT_FOUND"
DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"

# 409 Conflict Errors
CONFLICT = "CONFLICT"
DUPLICATE_PROJECT_NAME = "DUPLICATE_PROJECT_NAME"
DUPLICATE_EMAIL = "DUPLICATE_EMAIL"
RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"

# 429 Rate Limit / Subscription Limit Errors
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
SUBSCRIPTION_LIMIT_EXCEEDED = "SUBSCRIPTION_LIMIT_EXCEEDED"
PROJECT_LIMIT_EXCEEDED = "PROJECT_LIMIT_EXCEEDED"
REQUEST_QUOTA_EXCEEDED = "REQUEST_QUOTA_EXCEEDED"

# 402 Payment Required / Subscription Errors
SUBSCRIPTION_ERROR = "SUBSCRIPTION_ERROR"
SUBSCRIPTION_INACTIVE = "SUBSCRIPTION_INACTIVE"
SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED"

# ============================================================================
# 5xx Server Errors
# ============================================================================

# 500 Internal Server Error
INTERNAL_ERROR = "INTERNAL_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"
DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
DATABASE_INTEGRITY_ERROR = "DATABASE_INTEGRITY_ERROR"
OPERATION_FAILED = "OPERATION_FAILED"

# 502 Bad Gateway / External Service Errors
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
LLM_SERVICE_ERROR = "LLM_SERVICE_ERROR"
LLM_RATE_LIMIT = "LLM_RATE_LIMIT"
LLM_CONTEXT_LENGTH_EXCEEDED = "LLM_CONTEXT_LENGTH_EXCEEDED"
API_SERVICE_UNAVAILABLE = "API_SERVICE_UNAVAILABLE"

# 503 Service Unavailable
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"

# ============================================================================
# Error Code Categories (for documentation)
# ============================================================================

VALIDATION_ERROR_CODES = {
    VALIDATION_ERROR,
    INVALID_INPUT,
    MISSING_REQUIRED_FIELD,
    INVALID_PROJECT_TYPE,
    INVALID_PHASE,
    INVALID_SUBSCRIPTION_TIER,
}

AUTHENTICATION_ERROR_CODES = {
    AUTHENTICATION_FAILED,
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    MISSING_AUTH_HEADER,
}

AUTHORIZATION_ERROR_CODES = {
    UNAUTHORIZED,
    INSUFFICIENT_PERMISSIONS,
    ACCESS_DENIED,
    INSUFFICIENT_SUBSCRIPTION,
}

NOT_FOUND_ERROR_CODES = {
    NOT_FOUND,
    PROJECT_NOT_FOUND,
    USER_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    QUESTION_NOT_FOUND,
    NOTE_NOT_FOUND,
    DOCUMENT_NOT_FOUND,
    CONVERSATION_NOT_FOUND,
}

CONFLICT_ERROR_CODES = {
    CONFLICT,
    DUPLICATE_PROJECT_NAME,
    DUPLICATE_EMAIL,
    RESOURCE_ALREADY_EXISTS,
    INVALID_STATE_TRANSITION,
}

SUBSCRIPTION_ERROR_CODES = {
    SUBSCRIPTION_LIMIT_EXCEEDED,
    PROJECT_LIMIT_EXCEEDED,
    REQUEST_QUOTA_EXCEEDED,
    SUBSCRIPTION_ERROR,
    SUBSCRIPTION_INACTIVE,
    SUBSCRIPTION_CANCELLED,
}

RATE_LIMIT_ERROR_CODES = {
    RATE_LIMIT_EXCEEDED,
    LLM_RATE_LIMIT,
}

EXTERNAL_SERVICE_ERROR_CODES = {
    EXTERNAL_SERVICE_ERROR,
    LLM_SERVICE_ERROR,
    API_SERVICE_UNAVAILABLE,
}

DATABASE_ERROR_CODES = {
    DATABASE_ERROR,
    DATABASE_CONNECTION_ERROR,
    DATABASE_INTEGRITY_ERROR,
}

SERVER_ERROR_CODES = {
    INTERNAL_ERROR,
    OPERATION_FAILED,
    SERVICE_UNAVAILABLE,
    DATABASE_UNAVAILABLE,
}


# ============================================================================
# Error Code to HTTP Status Code Mapping
# ============================================================================

ERROR_CODE_TO_STATUS = {
    # 400 Validation
    VALIDATION_ERROR: 400,
    INVALID_INPUT: 400,
    MISSING_REQUIRED_FIELD: 400,
    INVALID_PROJECT_TYPE: 400,
    INVALID_PHASE: 400,
    INVALID_SUBSCRIPTION_TIER: 400,
    # 401 Authentication
    AUTHENTICATION_FAILED: 401,
    INVALID_CREDENTIALS: 401,
    TOKEN_EXPIRED: 401,
    TOKEN_INVALID: 401,
    MISSING_AUTH_HEADER: 401,
    # 403 Authorization
    UNAUTHORIZED: 403,
    INSUFFICIENT_PERMISSIONS: 403,
    ACCESS_DENIED: 403,
    INSUFFICIENT_SUBSCRIPTION: 403,
    # 404 Not Found
    NOT_FOUND: 404,
    PROJECT_NOT_FOUND: 404,
    USER_NOT_FOUND: 404,
    RESOURCE_NOT_FOUND: 404,
    QUESTION_NOT_FOUND: 404,
    NOTE_NOT_FOUND: 404,
    DOCUMENT_NOT_FOUND: 404,
    CONVERSATION_NOT_FOUND: 404,
    # 409 Conflict
    CONFLICT: 409,
    DUPLICATE_PROJECT_NAME: 409,
    DUPLICATE_EMAIL: 409,
    RESOURCE_ALREADY_EXISTS: 409,
    INVALID_STATE_TRANSITION: 409,
    # 429 Rate Limit
    RATE_LIMIT_EXCEEDED: 429,
    SUBSCRIPTION_LIMIT_EXCEEDED: 429,
    PROJECT_LIMIT_EXCEEDED: 429,
    REQUEST_QUOTA_EXCEEDED: 429,
    LLM_RATE_LIMIT: 429,
    # 402 Payment Required
    SUBSCRIPTION_ERROR: 402,
    SUBSCRIPTION_INACTIVE: 402,
    SUBSCRIPTION_CANCELLED: 402,
    # 500 Server Errors
    INTERNAL_ERROR: 500,
    DATABASE_ERROR: 500,
    DATABASE_CONNECTION_ERROR: 500,
    DATABASE_INTEGRITY_ERROR: 500,
    OPERATION_FAILED: 500,
    LLM_SERVICE_ERROR: 500,
    # 502 Bad Gateway
    EXTERNAL_SERVICE_ERROR: 502,
    API_SERVICE_UNAVAILABLE: 502,
    LLM_CONTEXT_LENGTH_EXCEEDED: 502,
    # 503 Service Unavailable
    SERVICE_UNAVAILABLE: 503,
    DATABASE_UNAVAILABLE: 503,
}
